# http://travis-ci.org/Crompulence/CPL_APP_OPENFOAM-3.0.1

os: linux
sudo: required
language: python
python:
    - 2.7

# set up build matrix
matrix:
  include:
    #Build for 14.04
    - dist: trusty
      env:
        - GCC_VERSION=7.2_conda
        - MPI=mpich3_conda 

branches:
  only:
    - master

cache:
  apt: true

install:

    #Get miniconda
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    #Create environment
    - conda create -q -n cplrun python=$TRAVIS_PYTHON_VERSION --no-default-packages
    - source activate cplrun
    - conda config --add channels edu159

    #We need to explicitly get gcc/gfortran as miniconda is not available for 5+ yet
    - conda install -y gxx_linux-64
    - conda install -y gfortran_linux-64

    #Here we install openfoam
    - conda install -c edu159 -y mpich
    - conda install -c edu159 -y openfoam

    #Numpy and mpi4py
    - conda install -y numpy 
    - conda install -c edu159 -y mpi4py

    #Setup aliases
    - FOAM_VERSION=3.0.1
    - FOAM_DIR_NAME=OpenFOAM-$FOAM_VERSION
    - ENVPREFIX=$HOME/miniconda/envs/cplrun

    #Go to virtual enviroment directory
    - cd $ENVPREFIX
    - git clone https://github.com/Crompulence/cpl-library.git ./cpl-library

    #Build CPL library using conda version of code
    - cd ./cpl-library
    - make PLATFORM=gcc
    - ldd lib/*
#    - cp lib/* $ENVPREFIX/lib
    - source SOURCEME.sh
    - cd ../

    #Get conda build so we can copy required stuff
    - git clone https://github.com/Crompulence/cpl_conda_builds.git ./cpl_conda_builds
    - RECIPE_DIR=$ENVPREFIX/cpl_conda_builds/cplapp-openfoam3.0.1/
    - cp -Rf ${RECIPE_DIR}/linux64Gcc $ENVPREFIX/opt/$FOAM_DIR_NAME/wmake/rules

    #Get all of CPL APP
#    - git clone https://github.com/Crompulence/CPL_APP_OPENFOAM-3.0.1.git ./CPL_APP_OPENFOAM-3.0.1
#    - cd CPL_APP_OPENFOAM-3.0.1/
    - cd /home/travis/build/Crompulence/CPL_APP_OPENFOAM-3.0.1/
    - echo "$ENVPREFIX/opt" > CODE_INST_DIR
    - source SOURCEME.sh
    #We need to make Pstream and patch the OpenFOAM version
    - wmake libso src/CPLPstream
#    - wmake libso src/CPLPstream 2>&1 | tee PStream_build.log | grep -i -B10 'error'
    - mv $FOAM_LIBBIN/$FOAM_MPI/libPstream.so $FOAM_LIBBIN/$FOAM_MPI/libPstream.so.orig
    - cp lib/libPstream.so $FOAM_LIBBIN/$FOAM_MPI/
    - make
#    - make 2>&1 | tee openfoam_build.log | grep -i -B10 'error'
#    - ldd bin/*
#    - ldd lib/*
    - cp lib/* $ENVPREFIX/lib
    - cp bin/* $ENVPREFIX/bin

script:
    - make test-hydrostatic
    - make test-fcc_dummy

after_success:
     - echo "Build Success"

#after_failure:
#    - cat /home/travis/build/Crompulence/CPL_APP_OPENFOAM-3.0.1/openfoam_build.log
                                                              
