#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

rm inletGasMassFlow
restore0Dir
runApplication blockMesh 
runApplication decomposePar

mpiexec -n 2 CPLinterFoamHardtPhaseChange -parallel : -n 2 python3 ./load_and_send_MD_data.py > log.CPLinterFoamHardtPhaseChange 2>&1 &
#------------------------------------------------------------------------------
