#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cplc++ minimal_MD.cpp -o MD

restore0Dir
runApplication blockMesh
runApplication decomposePar

mpiexec -n 2 CPLinterCondensatingEvaporatingFoam -parallel : -n 2 ./MD
#mpiexec -n 2 CPLinterCondensatingEvaporatingFoam -parallel : -n 2 python3 ./minimal_MD.py

#------------------------------------------------------------------------------
